### ISSUE TITLE
Functional approach

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-urgent-action-pdfs#5]
We don't have to take a functional approach. It seemed like a good one in this case and it's something I'd like to get my head around: 

So have an object as an input: in this case a defined set on regex terms to get. 

```
inputObject = {
 date: '/.*PUBLICATION DATE.*/g',
 number: '/.*URGENT ACTION TYPE AND NUMBER.*/g'
};
```

Push them through the different functions and emerge with an object at the other end. 

```
scrapedData = { 
   date: '5 July 2017', 
  number: 'THIRD UA 60/16' 
};
```

**Comment by pauldwaite** [comment]
Gotcha. The functional approach can work I think; the thing with Ramda is that it’s a functional programming library that also thinks every function should be curried (i.e. every function can return a function to be used later, instead of returning the actual value the function is there to work out).

That is a bit mind-bending if you haven’t worked that way before (which I haven’t).

A simpler way is indeed the way you’ve already got, which looks good: all your functions accept and return strings, so as you demonstrate, you can pass the results of one to another, either directly, or by storing the results in variables.

I’m going to try to work out the Ramda-style way of doing this, because as you say it is interesting, and seems worth getting our heads around.

One thing I would say is that it looks like we can assume with these PDFs that the way to get information from them is this:

1. Look for a prefix/label thingy, followed by a colon (e.g. `PUBLICATION DATE:`, `URGENT ACTION TYPE AND NUMBER:`)
2. Get all the text on that line following the colon.

As such, we can probably have an array or object of prefixes:

```
["PUBLICATION DATE", "URGENT ACTION TYPE AND NUMBER"]
// or
{date: "PUBLICATION DATE", number: "URGENT ACTION TYPE AND NUMBER"}
```

And then use Ramda functions to apply other functions to each of those, using the pdf text as input.

**Comment by pauldwaite** [comment]
(I’m just off to a festival, but hopefully I can have another look tomorrow afternoon, and actually be a bit more helpful.)
